    

def filter (choosen):
    professions = [
        'CEO',
        'M.D.',
        'Software Engineer',
        'Doctor',
        'Engineer',
        'Professor',
        'Coach',
        'Player',
        'Fencing Coach',
        'Attorney',
        'Architect',
        'Analyst',
        'Consultant',
        'Designer',
        'Developer',
        'Director',
        'Economist',
        'Editor',
        'Educator',
        'Executive',
        'Journalist',
        'Manager',
        'Musician',
        'Nurse',
        'Pharmacist',
        'Photographer',
        'Pilot',
        'Programmer',
        'Psychologist',
        'Researcher',
        'Scientist',
        'Software Engineer',
        'Surgeon',
        'Technician',
        'Therapist',
        'Writer',
        'Plumber',
        'Electrician',
        'Carpenter',
        'Welder',
        'Landscaper',
        'Actor',
        'Singer',
        'Dancer',
        'Artist',
        'Sales Representative',
        'Marketing Manager',
        'Advertising Executive',
        'Public Relations Specialist',
        'Physical Therapist',
        'Occupational Therapist',
        'Radiologic Technologist',
        'Speech-Language Pathologist',
        'Elementary School Teacher',
        'High School Teacher',
        'Special Education Teacher',
        'School Counselor',
        'Police Officer',
        'Firefighter',
        'Military Officer',
        'Politician',
        'Diplomat',
        'Astronaut',
        'Athlete',
        'Farmer',
        'Fisherman',
        'Rancher',
        'Forester',
        'Horticulturist',
        'Baker',
        'Butcher',
        'Candlestick Maker'
    ]
    popular_news_channels = [
    'BBC News', 'CNN', 'The Guardian', 'The New York Times', 'The Washington Post',
    'The Wall Street Journal', 'Reuters', 'Al Jazeera', 'The Associated Press', 'Bloomberg',
    'Forbes', 'ABC News', 'NBC News', 'CBS News', 'Fox News',
    'USA Today', 'The Huffington Post', 'CNBC', 'Time', 'Newsweek',
    'The Economist', 'Financial Times', 'Business Insider', 'Politico', 'NPR',
    'Sky News', 'Daily Mail', 'The Independent', 'The Telegraph', 'Los Angeles Times',
    'Chicago Tribune', 'The Boston Globe', 'San Francisco Chronicle', 'The Seattle Times', 'The Atlanta Journal-Constitution',
    'The Philadelphia Inquirer', 'The Dallas Morning News', 'The Denver Post', 'Miami Herald', 'The Arizona Republic',
    'The Globe and Mail', 'Toronto Star', 'National Post', 'Le Monde', 'Der Spiegel',
    'Frankfurter Allgemeine Zeitung', 'Süddeutsche Zeitung', 'El País', 'La Repubblica', 'Corriere della Sera',
    'The Times of India', 'Hindustan Times', 'The Hindu', 'China Daily', 'People\'s Daily',
    'The Sydney Morning Herald', 'The Age', 'The Asahi Shimbun', 'Yomiuri Shimbun', 'The Japan Times',
    'The Korea Herald', 'The Chosun Ilbo', 'The Straits Times', 'The Bangkok Post', 'The Jakarta Post',
    'The Moscow Times', 'Izvestia', 'Kommersant', 'The Times', 'The Sunday Times',
    'The Australian', 'The New Zealand Herald', 'Haaretz', 'The Jerusalem Post', 'Gulf News',
    'The Irish Times', 'The Scotsman', 'The Hindu', 'Dawn', 'The Express Tribune',
    'South China Morning Post', 'The Times of Israel', 'The Nation', 'The Star', 'The New Paper',
    'The Standard', 'The Mercury', 'The Star', 'The Daily Nation', 'The East African',
    'Al-Ahram', 'Al-Masry Al-Youm', 'Youm7', 'Ahram Online', 'Egypt Independent',
    ]
    popular_people = [
    'Marilyn Monroe', 'Abraham Lincoln', 'Nelson Mandela', 'Queen Elizabeth II', 'John F. Kennedy',
    'Martin Luther King', 'Winston Churchill', 'Donald Trump', 'Bill Gates', 'Muhammad Ali',
    'Mahatma Gandhi', 'Mother Teresa', 'Christopher Columbus', 'Charles Darwin', 'Elvis Presley',
    'Albert Einstein', 'Paul McCartney', 'Queen Victoria', 'Pope Francis', 'Jawaharlal Nehru',
    'Leonardo da Vinci', 'Vincent Van Gogh', 'Franklin D. Roosevelt', 'Pope John Paul II', 'Thomas Edison',
    'Rosa Parks', 'Lyndon Johnson', 'Ludwig Beethoven', 'Oprah Winfrey', 'Indira Gandhi',
    'Eva Peron', 'Benazir Bhutto', 'George Orwell', 'Vladimir Putin', 'Dalai Lama',
    'Walt Disney', 'Neil Armstrong', 'Peter Sellers', 'Barack Obama', 'Malcolm X',
    'J.K.Rowling', 'Richard Branson', 'Pele', 'Angelina Jolie', 'Jesse Owens',
    'John Lennon', 'Henry Ford', 'Haile Selassie', 'Joseph Stalin',
    'Amr Diab', 'Nancy Ajram', 'Elissa', 'Adel Emam', 'Hassan El Shafei',
    'Elias J. Corey', 'Ahmed Zewail', 'Ibn Khaldun'
    ]
    any = [
    'news', 'weather', 'sports', 'entertainment', 'technology',
    'health', 'finance', 'education', 'travel', 'food',
    'fashion', 'music', 'movies', 'games', 'jobs',
    'real estate', 'shopping', 'deals', 'science', 'politics',
    'relationships', 'fitness', 'pets', 'automotive', 'legal',
    'gardening', 'home improvement', 'art', 'history', 'geography',
    'mathematics', 'languages', 'literature', 'philosophy', 'psychology',
    'economics', 'biology', 'chemistry', 'physics', 'astronomy',
    'medicine', 'law', 'business', 'marketing', 'social media',
    'programming', 'coding', 'software', 'hardware', 'networking',
    'security', 'hacking', 'machine learning', 'data science', 'AI',
    'blockchain', 'cryptocurrency', 'bitcoin', 'ethereum', 'NFTs',
    'startups', 'entrepreneurship', 'investing', 'stocks', 'trading',
    'travel destinations', 'hotels', 'flights', 'vacations', 'tourism',
    'recipes', 'cooking', 'baking', 'nutrition', 'diets',
    'workouts', 'yoga', 'meditation', 'mental health', 'wellness',
    'dogs', 'cats', 'wildlife', 'nature', 'environment',
    'cars', 'motorcycles', 'electric vehicles', 'auto repair', 'car reviews',
    'legal advice', 'lawsuits', 'contracts', 'intellectual property', 'compliance',
    'DIY projects', 'interior design', 'landscaping', 'renovation', 'furniture',
    'painting', 'sculpture', 'photography', 'theatre', 'concert', 'festival', 'live performance',
    'art', 'gallery', 'painting', 'sculpture', 'exhibition',
    'movie', 'cinema', 'actor', 'director', 'hollywood',
    'book', 'novel', 'author', 'literature', 'poetry',
    'travel', 'vacation', 'adventure', 'tourism', 'destination',
    'food', 'restaurant', 'recipe', 'cuisine', 'cooking',
    'fashion', 'clothing', 'designer', 'runway', 'style',
    'technology', 'gadget', 'smartphone', 'app', 'software',
    'health', 'fitness', 'nutrition', 'diet', 'exercise',
    'sports', 'game', 'athlete', 'competition', 'workout',
    'education', 'school', 'university', 'student', 'teacher',
    'business', 'finance', 'economy', 'startup', 'entrepreneur',
    'science', 'research', 'innovation', 'discovery', 'experiment',
    'politics', 'government', 'election', 'policy', 'law',
    'environment', 'nature', 'wildlife', 'conservation', 'climate',
    'history', 'culture', 'tradition', 'heritage', 'archaeology',
    'psychology', 'mind', 'behavior', 'therapy', 'counseling',
    'philosophy', 'ethics', 'logic', 'metaphysics', 'epistemology',
    'mathematics', 'geometry', 'algebra', 'calculus', 'statistics',
    'engineering', 'mechanics', 'electronics', 'robotics', 'aerospace'
  ]

    if choosen == "Profession":
        return professions
    if choosen == "News" :
        return popular_news_channels
    if choosen == "Person":
        return popular_people
    if choosen == "General":
        return any

