    

def get_professions ():
    professions = [
        'CEO',
        'M.D.',
        'Software Engineer',
        'Doctor',
        'Engineer',
        'Professor',
        'Coach',
        'Player',
        'Fencing Coach',
        'Attorney',
        'Architect',
        'Analyst',
        'Consultant',
        'Designer',
        'Developer',
        'Director',
        'Economist',
        'Editor',
        'Educator',
        'Executive',
        'Journalist',
        'Manager',
        'Musician',
        'Nurse',
        'Pharmacist',
        'Photographer',
        'Pilot',
        'Programmer',
        'Psychologist',
        'Researcher',
        'Scientist',
        'Software Engineer',
        'Surgeon',
        'Technician',
        'Therapist',
        'Writer',
        'Plumber',
        'Electrician',
        'Carpenter',
        'Welder',
        'Landscaper',
        'Actor',
        'Singer',
        'Dancer',
        'Artist',
        'Sales Representative',
        'Marketing Manager',
        'Advertising Executive',
        'Public Relations Specialist',
        'Physical Therapist',
        'Occupational Therapist',
        'Radiologic Technologist',
        'Speech-Language Pathologist',
        'Elementary School Teacher',
        'High School Teacher',
        'Special Education Teacher',
        'School Counselor',
        'Police Officer',
        'Firefighter',
        'Military Officer',
        'Politician',
        'Diplomat',
        'Astronaut',
        'Athlete',
        'Farmer',
        'Fisherman',
        'Rancher',
        'Forester',
        'Horticulturist',
        'Baker',
        'Butcher',
        'Candlestick Maker'
    ]
    return [profession.split(' ')[0] for profession in professions]

